name: Build Kivy APK with Build-tools fix

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential zip unzip openjdk-17-jdk \
          libncurses6 libstdc++6 zlib1g-dev libffi-dev libssl-dev git
        pip install --upgrade pip
        pip install cython buildozer

    - name: Install Android Build-tools 30.0.3
      run: |
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "build-tools;30.0.3"

    - name: Build APK
      working-directory: ./apps
      run: |
        buildozer android debug --verbose

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: apps/bin/*.apk
