name: Build Kivy Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool pkg-config \
              libffi-dev libssl-dev zlib1g-dev \
              git zip unzip libncurses5-dev libncursesw5-dev libtinfo5 cmake \
              openjdk-17-jdk python3-pip
          pip3 install --user Cython buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Set up Android SDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/
          echo "Listing sdkmanager location:"
          ls $ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          echo "sdkmanager version:"
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --version
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
              --sdk_root=$ANDROID_SDK_ROOT \
              "build-tools;30.0.3" "platforms;android-30"

      - name: Build Android (Kivy)
        working-directory: apps
        run: buildozer android debug --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: apps/bin/*.apk
