name: Build APK

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install OS dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          automake \
          build-essential \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses6 \
          unzip \
          openjdk-17-jdk \
          python3-pip

    - name: Install Buildozer and Cython
      run: |
        python3 -m pip install --upgrade pip
        pip install buildozer cython

    - name: Set environment variables
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$HOME/android-ndk" >> $GITHUB_ENV

    - name: Download Android SDK Command Line Tools
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip sdk-tools.zip
        rm sdk-tools.zip
        mv cmdline-tools latest

    - name: Accept Android Licenses
      run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install Android platform tools
      run: |
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
          --sdk_root=$ANDROID_SDK_ROOT \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;30.0.3" \
          "ndk;25.2.9519653"

    - name: Set ANDROIDNDK for Buildozer
      run: echo "ANDROIDNDK=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV

    - name: Build APK
      working-directory: apps
      run: buildozer android debug
