name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: $RUNNER_TEMP/android-sdk
      ANDROID_NDK_ROOT: $RUNNER_TEMP/android-ndk
      ANDROID_API: 31
      ANDROID_BUILD_TOOLS_VERSION: 30.0.3
      ANDROID_MIN_API: 21

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5 \
            libtinfo5

      - name: Install Buildozer and dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install cython buildozer

      - name: Download Android SDK cmdline-tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools.zip
          rm commandlinetools.zip
          mv cmdline-tools latest

      - name: Install Android SDK build tools and platforms
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --install "platform-tools" "platforms;android-$ANDROID_API" "build-tools;$ANDROID_BUILD_TOOLS_VERSION"
        shell: bash

      - name: Build APK with Buildozer
        working-directory: ./apps/your_app_folder   # <-- اینجا مسیر اپلیکیشن خودت رو بذار
        run: |
          buildozer android debug
