Ú†name: Build Kivy APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential zip unzip openjdk-17-jdk \
          libncurses5 libstdc++6 zlib1g-dev libffi-dev libssl-dev git
        pip install --upgrade pip
        pip install cython==0.29.36 buildozer==1.5.0

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
