name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: نصب وابستگی‌های سیستمی
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip \
                              autoconf libtool pkg-config zlib1g-dev \
                              libncurses5-dev libncursesw5-dev libtinfo6 \
                              cmake libffi-dev libssl-dev

      - name: نصب Buildozer و Cython
        run: |
          pip3 install --upgrade --user buildozer cython==0.29.33

      - name: Setup Android SDK command-line tools
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          wget -qO cmdlinetools.zip \
            https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip cmdlinetools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          if [ -d "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" ]; then
            mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools \
               $ANDROID_SDK_ROOT/cmdline-tools/latest
          else
            mv $ANDROID_SDK_ROOT/cmdline-tools \
               $ANDROID_SDK_ROOT/cmdline-tools/latest
          fi

      - name: نصب Android SDK platforms و build-tools
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
            --sdk_root=$ANDROID_SDK_ROOT "platform-tools" \
            "platforms;android-30" "build-tools;30.0.3"

      - name: ساخت اپلیکیشن با Buildozer
        run: |
          cd apps
          yes | buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: apps/bin/*.apk
